### PR TITLE
update to netcore 3.1

### PR DESCRIPTION
**Pull request by srkirkland**
updates projects to core3.1, including all nuget libraries and most js libraries (react dependencies kept the same).

### CODE REVIEW

**Comment by srkirkland** [comment]
@sprucely interesting, I don't see that error, at least when running against the testdb

**Comment by sprucely** [comment]
@srkirkland Yeah, and I would hope that it's not actually attempting to alter the database unless `FK_RequestHistory_Requests_RequestId` actually is missing. But it is bubbling up from `SqlConnection.OnError()`.

**Comment by sprucely** [comment]
I got the connection string from the tacos-test config on portal.azure.com.

**Comment by srkirkland** [comment]
from my logging it doesn't look like for me it's actually running the db recreate since the db is already created.  I'm not sure why it would for you -- are you putting the value into usersecrets using the `ConnectionStrings:DefaultConnection` key?

**Comment by sprucely** [comment]
@srkirkland Yep. The stack trace is getting as far as Calling SqlServerDatabaseCreator.CreateTables() , which indicates it is detecting that the database exists, but that it is not finding any non-system tables. When I used my local SqlExpress, it created the tacos database, but did not create any tables.

**Comment by sprucely** [comment]
Here's the sql it's using to detect user tables...
```sql
IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
```

For the testdb, I would have guessed that it was a permission issue with accessing system tables. But that wouldn't explain why I'm having the same problem with my local db.

**Pull request merged**
